enum Currency {
    EUR = 'EUR',
    USD = 'USD',
    GBP = 'GBP',
    JPY = 'JPY',
    CHF = 'CHF',
    CAD = 'CAD',
    AUD = 'AUD',
    NZD = 'NZD',
    CNY = 'CNY',
    INR = 'INR',
    MXN = 'MXN',
    SGD = 'SGD',
    HKD = 'HKD',
    NOK = 'NOK',
    SEK = 'SEK',
    DKK = 'DKK',
    CZK = 'CZK',
    HUF = 'HUF',
    PLN = 'PLN',
    RUB = 'RUB',
    TRY = 'TRY',
    BRL = 'BRL',
    ZAR = 'ZAR',
    KRW = 'KRW',
    THB = 'THB',
}

export { Currency };
